	const_def
	const POKEDEX_DIGLETT
	const POKEDEX_GASTLY
	const POKEDEX_OMANYTE
	const POKEDEX_MUK
	const POKEDEX_KABUTO
	const POKEDEX_RATTATA
	const POKEDEX_JIGGLYPUFF
	const POKEDEX_MANKEY
	const POKEDEX_SLOWPOKE
	const POKEDEX_POLIWAG
	const POKEDEX_PARASECT
	const POKEDEX_VENONAT
	const POKEDEX_POLIWHIRL
	const POKEDEX_DRAGONAIR
	const POKEDEX_CHARIZARD
	const POKEDEX_CHANSEY
	const POKEDEX_PORYGON
	const POKEDEX_GENGAR
	const POKEDEX_DITTO
	const POKEDEX_BELLSPROUT
	const POKEDEX_HAUNTER
	const POKEDEX_KOFFING
	const POKEDEX_PINSIR
	const POKEDEX_HORSEA
	const POKEDEX_NIDORAN_F
	const POKEDEX_DRATINI
	const POKEDEX_WEEPINBELL
	const POKEDEX_STARYU
	const POKEDEX_DUGTRIO
	const POKEDEX_VENUSAUR
	const POKEDEX_DROWZEE
	const POKEDEX_SEADRA
	const POKEDEX_NIDORAN_M
	const POKEDEX_WIGGLYTUFF
	const POKEDEX_MAGMAR
	const POKEDEX_IVYSAUR
	const POKEDEX_KAKUNA
	const POKEDEX_CLEFAIRY
	const POKEDEX_SPEAROW
	const POKEDEX_STARMIE
	const POKEDEX_ZUBAT
	const POKEDEX_VOLTORB
	const POKEDEX_CLOYSTER
	const POKEDEX_EXEGGUTOR
	const POKEDEX_MAGIKARP
	const POKEDEX_SEEL
	const POKEDEX_SHELLDER
	const POKEDEX_MEOWTH
	const POKEDEX_FEAROW
	const POKEDEX_WEEDLE
	const POKEDEX_MAGNEMITE
	const POKEDEX_SCYTHER
	const POKEDEX_VULPIX
	const POKEDEX_METAPOD
	const POKEDEX_VENOMOTH
	const POKEDEX_ELECTABUZZ
	const POKEDEX_TANGELA
	const POKEDEX_GOLDEEN
	const POKEDEX_NIDOQUEEN
	const POKEDEX_GYARADOS
	const POKEDEX_PERSIAN
	const POKEDEX_DODRIO
	const POKEDEX_JOLTEON
	const POKEDEX_GOLDUCK
	const POKEDEX_MR_MIME
	const POKEDEX_BUTTERFREE
	const POKEDEX_GRAVELER
	const POKEDEX_RATICATE
	const POKEDEX_ALAKAZAM
	const POKEDEX_KANGASKHAN
	const POKEDEX_GLOOM
	const POKEDEX_PONYTA
	const POKEDEX_NIDORINO
	const POKEDEX_NIDOKING
	const POKEDEX_BLASTOISE
	const POKEDEX_PRIMEAPE
	const POKEDEX_MACHOKE
	const POKEDEX_RAPIDASH
	const POKEDEX_GRIMER
	const POKEDEX_ONIX
	const POKEDEX_MACHAMP
	const POKEDEX_VILEPLUME
	const POKEDEX_PARAS
	const POKEDEX_LAPRAS
	const POKEDEX_BULBASAUR
	const POKEDEX_MACHOP
	const POKEDEX_MAGNETON
	const POKEDEX_SEAKING
	const POKEDEX_SQUIRTLE
	const POKEDEX_DRAGONITE
	const POKEDEX_OMASTAR
	const POKEDEX_GROWLITHE
	const POKEDEX_VAPOREON
	const POKEDEX_FARFETCHD
	const POKEDEX_BEEDRILL
	const POKEDEX_GOLEM
	const POKEDEX_FLAREON
	const POKEDEX_CHARMANDER
	const POKEDEX_KRABBY
	const POKEDEX_CUBONE
	const POKEDEX_ARBOK
	const POKEDEX_RHYHORN
	const POKEDEX_NINETALES
	const POKEDEX_ABRA
	const POKEDEX_MEWTWO
	const POKEDEX_RHYDON
	const POKEDEX_RAICHU
	const POKEDEX_TAUROS
	const POKEDEX_HITMONLEE
	const POKEDEX_CLEFABLE
	const POKEDEX_LICKITUNG
	const POKEDEX_EEVEE
	const POKEDEX_PIKACHU
	const POKEDEX_CATERPIE
	const POKEDEX_NIDORINA
	const POKEDEX_MAROWAK
	const POKEDEX_ARCANINE
	const POKEDEX_KADABRA
	const POKEDEX_VICTREEBEL
	const POKEDEX_MOLTRES
	const POKEDEX_DODUO
	const POKEDEX_JYNX
	const POKEDEX_GOLBAT
	const POKEDEX_SANDSLASH
	const POKEDEX_TENTACRUEL
	const POKEDEX_PIDGEOT
	const POKEDEX_DEWGONG
	const POKEDEX_KINGLER
	const POKEDEX_SNORLAX
	const POKEDEX_EXEGGCUTE
	const POKEDEX_WEEZING
	const POKEDEX_ELECTRODE
	const POKEDEX_AERODACTYL
	const POKEDEX_WARTORTLE
	const POKEDEX_ARTICUNO
	const POKEDEX_HITMONCHAN
	const POKEDEX_SLOWBRO
	const POKEDEX_PIDGEOTTO
	const POKEDEX_HYPNO
	const POKEDEX_KABUTOPS
	const POKEDEX_SANDSHREW
	const POKEDEX_EKANS
	const POKEDEX_POLIWRATH
	const POKEDEX_CHARMELEON
	const POKEDEX_PSYDUCK
	const POKEDEX_ODDISH
	const POKEDEX_TENTACOOL
	const POKEDEX_PIDGEY
	const POKEDEX_GEODUDE
	const POKEDEX_ZAPDOS
	const POKEDEX_MEW

pushc
newcharmap dexnames

charmap "ア", 0
charmap "イ", 1
charmap "ウ", 2
charmap "エ", 3
charmap "オ", 4
charmap "カ", 5
charmap "キ", 6
charmap "ク", 7
charmap "ケ", 8
charmap "コ", 9
charmap "サ", 10
charmap "シ", 11
charmap "ス", 12
charmap "セ", 13
charmap "ソ", 14
charmap "タ", 15
charmap "チ", 16
charmap "ツ", 17
charmap "テ", 18
charmap "ト", 19
charmap "ナ", 20
charmap "ニ", 21
charmap "ヌ", 22
charmap "ネ", 23
charmap "ノ", 24
charmap "ハ", 25
charmap "ヒ", 26
charmap "フ", 27
charmap "ヘ", 28
charmap "ホ", 29
charmap "マ", 30
charmap "ミ", 31
charmap "ム", 32
charmap "メ", 33
charmap "モ", 34
charmap "ヤ", 35
charmap "ユ", 36
charmap "ヨ", 37
charmap "ラ", 38
charmap "リ", 39
charmap "ル", 40
charmap "レ", 41
charmap "ロ", 42
charmap "ワ", 43
charmap "ヲ", 44
charmap "ン", 45
charmap "ァ", 46
charmap "ィ", 47
charmap "ゥ", 48
charmap "ェ", 49
charmap "ォ", 50
charmap "ャ", 51
charmap "ュ", 52
charmap "ョ", 53
charmap "ッ", 54
charmap "ー", 55
charmap "0", 56
charmap "1", 57
charmap "2", 58
charmap "3", 59
charmap "4", 60
charmap "5", 61
charmap "6", 62
charmap "7", 63
charmap "8", 64
charmap "9", 65
charmap ":", 66
charmap "<BALL>", 67
charmap "?", 68

charmap " ", 95

charmap "♂", 252
charmap "♀", 253
charmap "゛", 254
charmap "゜", 255

popc
